package com.logicaldoc.core.runtime;

/**
 * Enumeration of relevant aspects
 * 
 * @author Marco Meschieri - LogicalDOC
 * @since 9.2.2
 */
public enum Aspect {
	AI, STORING, SENDINGMESSAGES, EVENTSGATHERING, SAVEHISTORY, INITIALIZATION, VALIDATION, CUSTOMID, UNIQUENESSFILENAME, WRITECHECK, SCHEDULEDTASKS, AUTOMATION, ANTIVIRUS, WORKSPACEQUOTACHECK, FORMPROCESSING, AUTONAMING, AUTOFOLDING, AUTOREVISIONING, SAVEAPICALL, WORKFLOW, AUTOFILL;
}