package com.logicaldoc.core.runtime;

import java.util.Arrays;

/**
 * Enumeration of relevant feature codes
 * 
 * @author Marco Meschieri - LogicalDOC
 * @since 9.2.2
 */
public enum Feature {
	IMPORT_REMOTE_FOLDERS, ADDITIONAL_FORMATS, OCR, IMPEX, TAGS, BRANDING_STANDARD, DIGITAL_SIGNATURE, PDF, LICENSE, EMAIL_IMPORT, TRASH, SAVED_SEARCHES, MESSAGES, INCREMENTAL_ARCHIVES, SINGLE_SIGNON, SCAN, AUDIT, NOTIFICATIONS, WORKFLOW, OFFICE, ENTERPRISE_SEARCH, NOTES, TAGS_ADMIN, GUI_LANGUAGES, INDEX_LANGUAGES, TASK_REPORT_NOTIFICATION, SPLIT, BULK_UPDATE, CMIS, MOBILE_APPS, CUSTOM_ACTIONS, BULK_CHECKOUT, WEBCONTENT, COMPARISON, UPDATES, MOBILE_GUI, BRANDING_FULL, BRANDING_LOGO, BRUTEFORCE_ATTACK_PREVENTION, SHOW_LICENSEE, PATCHES, FOLDER_TEMPLATE, GOOGLE_DRIVE, SMB_STORE, FORMAT_CONVERSION, CLOUD_STORE, ROBOT, AUTOMATION, ZONAL_OCR, SHOW_DISABLED, PREVIEW, MULTI_STORE, BOOKMARKS, CUSTOMID, LDAP, TEMPLATE, PROTOCOLS, WEBSERVICE, WEBDAV, EXPORT, IMPORT_LOCAL_FOLDERS, PARAMETRIC_SEARCHES, DROP_SPOT, BARCODES, QUOTAS, DUPLICATES_DISCOVERY, REPO_ENCRYPTION, LEGALS, EXPORT_CSV, RETENTION_POLICIES, MULTI_WORKSPACE, CLUSTERING, FIREWALL, CALENDAR, FTP, BACKUP, KOFAX, SYNC, MULTI_TENANT, DROPBOX, ANTIVIRUS, ANNOTATIONS, ARCHIVING, SHAREFILE, STAMP, FORM, CUSTOM_REPORTS, AUTO_NAMING, AUTO_FOLDING, DOCUSIGN, HOT_FOLDER, REVISION, WEBDAV_BASIC, TWO_FACTORS_AUTHENTICATION, CHAT, SYNDICATION, GEOLOCATION, ZONAL_BARCODE, WEB_FORM, DIGITAL_SIGNATURE_CLIENT, VIEW_TICKET, READING_CONFIRMATION, TECHNICAL_SUPPORT, CHATGPT, GOOGLE_CALENDAR, SCANNER, ONLYOFFICE, ARTIFICIAL_INTELLIGENCE, SEMANTIC_SEARCHES, AUTOFILL;

	/**
	 * Gets the right enumeration entry from the corresponding string
	 * 
	 * @param key the key in license
	 * 
	 * @return The corresponding entry
	 */
	public static Feature fromKey(String key) {
		return Arrays.asList(values()).stream().filter(e -> key.equals(e.key())).findFirst().orElseThrow();
	}

	/**
	 * Converts the enumeration entry to the corresponding key in the license
	 * 
	 * @return The key
	 */
	public String key() {
		return "Feature_" + (ordinal() + 1);
	}

	@Override
	public String toString() {
		return key();
	}
}