isc.DataSource.create({
    isServerDS:true,
    allowAdvancedCriteria:true,
    description:"A thing which runs Quartz Jobs",
    ID:"QuartzJobs",
    fields:[
        {
            name:"group",
            type:"string",
            required:true,
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"name",
            type:"string",
            required:true,
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"description",
            type:"string",
            validators:[
            ]
        },
        {
            name:"className",
            type:"string",
            required:true,
            validators:[
            ]
        },
        {
            name:"durability",
            type:"boolean",
            defaultValue:"true",
            validators:[
            ]
        },
        {
            name:"recover",
            type:"boolean",
            defaultValue:"true",
            validators:[
            ]
        },
        {
            name:"dataMap",
            type:"any",
            validators:[
            ]
        }
    ]
})
