isc.DataSource.create({
    inheritsFrom:"DataSource",
    Constructor:"XSComplexType",
    isServerDS:true,
    allowAdvancedCriteria:true,
    addGlobalId:false,
    ID:"XSComplexType",
    fields:[
    ]
})
